### ISSUE TITLE
Tests to verify mcu and targets yaml files

### ISSUE THREAD

**Issue by 0xc0170** [project-generator/project_generator_definitions#13]
We should add simple CI tests to at least verify syntax in the yaml files.

Core should be valid, target should have mcu, and mcu should be valid and present. All tool specific should be there. For example this can be normal mistake for user adding a new target:

```
    iar:
    OGChipSelectEditMenu:
      state:
      - STM32F401xE ST STM32F401xE
    OGCoreOrChip:
      state:
      - 1
```

The tests would be run by Travis, so each PR would be tested before it gets landed
