### ISSUE TITLE
Adding a new board

### ISSUE THREAD

**Issue by Ashleyvk** [project-generator/project_generator_definitions#145]
Hi,
I want to add a new board, stm32f373cc as an HIC. When I try to generate the make file using progen, I get the following error:
RuntimeError: Target: stm32f373cc not found, Please add the target to https://github.com/project-generator/project_generator_definitions
Any suggestions on what can be done? How do we add a new mcu yaml file to project generator definition?

**Comment by Ashleyvk** [comment]
Any suggestions on this?

**Comment by 0xc0170** [comment]
Sorry for the delay.

Adding the `stm32f373cc ` should be fairly simple. 

Create yaml file under mcu/st and all it's needed:

```
mcu:
    vendor:
        - st
    name:
        - stm32f373cc
    core:
        - cortex-m4
```
