### ISSUE TITLE
uvision4/5 mcu definition options

### ISSUE THREAD

**Issue by ohagendorf** [project-generator/project_generator_definitions#77]
Every uvision and uvision5 option block should contain the following otions:

```
    uvision(5):
        TargetOption:
            Device:
            - xx
            DeviceId:
            - xx
            Vendor:
            - xx
            Cpu:
            - xx
            FlashDriverDll:
            - xx
            SFDFile:
            - xx
            RegisterFile:
            - xx
```

This is optional:

```
            PackID:
            - xx
```

The PR project-generator/project_generator#381 extended the options.
